# Generated by Django 3.0.6 on 2020-05-24 18:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_valves', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time', models.IntegerField()),
                ('valves_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('stopped_manually', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='irrigation.Sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'irrigation',
            },
        ),
    ]
