# Generated by Django 3.1.1 on 2020-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20200919_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisture',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
